<?php
// +----------------------------------------------------------------------
// | 萤火商城系统 [ 致力于通过产品和服务，帮助商家高效化开拓市场 ]
// +----------------------------------------------------------------------
// | Copyright (c) 2017~2021 https://www.yiovo.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed 这不是一个自由软件，不允许对程序代码以任何形式任何目的的再发行
// +----------------------------------------------------------------------
// | Author: 萤火科技 <admin@yiovo.com>
// +----------------------------------------------------------------------
declare (strict_types = 1);

namespace app\index\controller;

use app\api\model\Store;
use app\common\model\Muban;
use app\common\model\User;
use app\common\model\user\Play;
use app\common\model\user\PlayPreview;
use cores\BaseController;
use dh2y\qrcode\QRcode;
use think\facade\View;

/**
 * 首页
 * Class help
 */
class Index extends BaseController
{
    public $runBackUrl = 'https://mp.weixin.qq.com/s/iNR3BdbjvGucZR2vzc48sw'; //返回的链接
    public $gengduoUrl = 'https://mp.weixin.qq.com/s/iNR3BdbjvGucZR2vzc48sw'; //点击更多的链接
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $store = Store::detail(10001);
        $this->runBackUrl = isset($store['fanghui_link'])?$store['fanghui_link']:'https://mp.weixin.qq.com/s/iNR3BdbjvGucZR2vzc48sw';
        $this->gengduoUrl = isset($store['gengduo_link'])?$store['gengduo_link']:'https://mp.weixin.qq.com/s/iNR3BdbjvGucZR2vzc48sw';
    }

    /**
     * 判断是否SSL协议
     * @return boolean
     */
    function is_ssl() {
        if(isset($_SERVER['HTTPS']) && ('1' == $_SERVER['HTTPS'] || 'on' == strtolower($_SERVER['HTTPS']))){
            return true;
        }else if(isset($_SERVER['SERVER_PORT']) && ('443' == $_SERVER['SERVER_PORT'] )) {
            return true;
        }
        return false;

    }
    /**
     * 获取列表记录
     */
    public function index()
    {
        $http = 'http://';
        $http =$this->is_ssl() ? 'https://'  : $http;
        $host = $http.$_SERVER['HTTP_HOST'];
        $param = $this->request->param();
        $runBack = isset($param['runBack'])?$param['runBack']:1;
        $runBackUrl = $this->runBackUrl;
        $gengduoUrl = $this->gengduoUrl;
        $id = isset($param['id'])?$param['id']:null; //用户创建的id

        //判断id的信息
        if($id == null){
            View::assign('runBackUrl',$runBackUrl);
            View::assign('gengduoUrl',$gengduoUrl);
            return View::fetch('error');
        }else{
//            $play = Play::detail((int)$id); //获取模板信息
            $plays = new Play();
            $play = $plays->where('domain','=',$host)->where('num','=',$id)->find();
            if($play == null){
                $play = $plays->where('domain','=',$_SERVER['HTTP_HOST'])->where('num','=',$id)->find();
            }
            if($play == null){
                View::assign('runBackUrl',$runBackUrl);
                View::assign('gengduoUrl',$gengduoUrl);
                return View::fetch('error');
            }
            if($play['is_delete'] == 1){
                View::assign('runBackUrl',$runBackUrl);
                View::assign('gengduoUrl',$gengduoUrl);
                return View::fetch('error');
            }
            $play->save(['see_num'=>$play['see_num']+1]); //预览加一
            if($play['is_jump'] == 1){ //是否跳转
                if($play['see_jump_num'] == 0){
                    header("Location:".$play['jump_link']);
                    exit;
                }else{
                    if($play['see_num'] > $play['see_jump_num']){
                        header("Location:".$play['jump_link']);
                        exit;
                    }
                }
            }
            $user = User::detail($play['user_id']);
            if(isset($user['gengduo_link']) && $user['gengduo_link'] != null){
                $gengduoUrl = $user['gengduo_link'];
            }
            if(isset($user['fanghui_link']) && $user['fanghui_link'] != null){
                $runBackUrl = $user['fanghui_link'];
            }
            $data = json_decode($play['data_json'],true);
            //字符串转Unicode编码
            $blessing = isset($data['blessing'])?$data['blessing']:'';
            if($blessing != null && $play['category_id'] !=5 ){
                $blessing = preg_replace('/\n/','<br/>',$blessing);
//                $blessing = $this->unicode_encode($blessing);
                $data['blessing'] = $blessing;
            }
            $next_text = isset($data['next_text'])?$data['next_text']:'';
            if($next_text != null){
                $next_text = preg_replace('/\n/','<br/>',$next_text);
//                $next_text = $this->unicode_encode($next_text);
                $data['next_text'] = $next_text;
            }
            View::assign('data',$data);
            View::assign('id',$id);
            View::assign('runBack',$runBack);
            View::assign('runBackUrl',$runBackUrl);
            View::assign('gengduoUrl',$gengduoUrl);
            return View::fetch('index'.$play['category_id']);
        }
    }


    /**
     * 小程序预览
     */
    public function playPreview()
    {
        $param = $this->request->param();
        $runBack = isset($param['runBack'])?$param['runBack']:1;
        $runBackUrl = $this->runBackUrl;
        $gengduoUrl = $this->gengduoUrl;
        $id = isset($param['id'])?$param['id']:null; //用户创建的id
        View::assign('runBack',$runBack);
        View::assign('runBackUrl',$runBackUrl);
        View::assign('gengduoUrl',$gengduoUrl);
        //判断id的信息
        if($id == null){
            return View::fetch('error');
        }else{
            $play = PlayPreview::detail((int)$id); //获取模板信息
            if($play == null){
                return View::fetch('error');
            }
            View::assign('id',$id);
            $data = json_decode(urldecode($play['data_json']),true);
            //字符串转Unicode编码
            $blessing = isset($data['blessing'])?$data['blessing']:'';
            if($blessing != null && $play['category_id'] !=5 ){
                $blessing = preg_replace('/\n/','<br/>',$blessing);
//                $blessing = $this->unicode_encode($blessing);
                $data['blessing'] = $blessing;
            }
            $next_text = isset($data['next_text'])?$data['next_text']:'';
            if($next_text != null){
                $next_text = preg_replace('/\n/','<br/>',$next_text);
//                $next_text = $this->unicode_encode($next_text);
                $data['next_text'] = $next_text;
            }
//            print_r($data);exit;
            View::assign('data',$data);
            return View::fetch('index'.$play['category_id']);
        }
    }

    /**
     * @return string
     * pc预览页面
     */
    public function preview(){
        $param = $this->request->param();
        $runBack = false;
        $runBackUrl = $this->runBackUrl;
        $gengduoUrl = $this->gengduoUrl;
        View::assign('runBack',$runBack);
        View::assign('runBackUrl',$runBackUrl);
        View::assign('gengduoUrl',$gengduoUrl);
        $category_id = isset($param['category_id'])?$param['category_id']:null; //创建的模板类型 用于预览
        $data_json = isset($param['data_json'])?$param['data_json']:null; //用户创建的模板内容
        $data_json = htmlspecialchars_decode($data_json);
        if(is_null(json_decode($data_json)) || $category_id == null){
            return View::fetch('error');
        }
        $data = json_decode($data_json,true);
        //字符串转Unicode编码
        $blessing = isset($data['blessing'])?$data['blessing']:'';
        if($blessing != null && $category_id !=5){
            $blessing = preg_replace('/\n/','<br/>',$blessing);
//            $blessing = $this->unicode_encode($blessing);
            $data['blessing'] = $blessing;
        }
        $next_text = isset($data['next_text'])?$data['next_text']:'';
        if($next_text != null){
            $next_text = preg_replace('/\n/','<br/>',$next_text);
//            $next_text = $this->unicode_encode($next_text);
            $data['next_text'] = $next_text;
        }
        View::assign('data',$data);
        return View::fetch('index'.$category_id);
    }

    //字符串转Unicode编码
    function unicode_encode($strLong) {
        $strArr = preg_split('/(?<!^)(?!$)/u', $strLong);//拆分字符串为数组(含中文字符)
        $resUnicode = '';
        foreach ($strArr as $str)
        {
            $bin_str = '';
            $arr = is_array($str) ? $str : str_split($str);//获取字符内部数组表示,此时$arr应类似array(228, 189, 160)
            foreach ($arr as $value)
            {
                $bin_str .= decbin(ord($value));//转成数字再转成二进制字符串,$bin_str应类似111001001011110110100000,如果是汉字"你"
            }
            $bin_str = preg_replace('/^.{4}(.{4}).{2}(.{6}).{2}(.{6})$/', '$1$2$3', $bin_str);//正则截取, $bin_str应类似0100111101100000,如果是汉字"你"
            $unicode = dechex(bindec($bin_str));//返回unicode十六进制
            $_sup = '';
            for ($i = 0; $i < 4 - strlen($unicode); $i++)
            {
                $_sup .= '0';//补位高字节 0
            }
            $str =  '\\u' . $_sup . $unicode; //加上 \u  返回
            $resUnicode .= $str;
        }
        return $resUnicode;
    }
//Unicode编码转字符串方法1
    function unicode_decode($name)
    {
        // 转换编码，将Unicode编码转换成可以浏览的utf-8编码
        $pattern = '/([\w]+)|(\\\u([\w]{4}))/i';
        preg_match_all($pattern, $name, $matches);
        if (!empty($matches))
        {
            $name = '';
            for ($j = 0; $j < count($matches[0]); $j++)
            {
                $str = $matches[0][$j];
                if (strpos($str, '\\u') === 0)
                {
                    $code = base_convert(substr($str, 2, 2), 16, 10);
                    $code2 = base_convert(substr($str, 4), 16, 10);
                    $c = chr($code).chr($code2);
                    $c = iconv('UCS-2', 'UTF-8', $c);
                    $name .= $c;
                }
                else
                {
                    $name .= $str;
                }
            }
        }
        return $name;
    }
//Unicode编码转字符串
    function unicode_decode2($str){
        $json = '{"str":"' . $str . '"}';
        $arr = json_decode($json, true);
        if (empty($arr)) return '';
        return $arr['str'];
    }

}
